name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    name: PHP ${{ matrix.php-versions }} Tests
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.3', '8.4']

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpstan@v3
        with:
          path: src/